name: Template Tests

on:
    workflow_call:

jobs:
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checking Source Code
              uses: actions/checkout@v4
            
            - name: Setting up Python
              uses: actions/setup-python@v4
              with:
                python-version: 3.10

            - name: Installing Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Running the tests
              run: |
                pytest --cov=test--cov-report=html --html=test-report.html --self-contained-html
            
            - name: Sending test results
              uses: actions/upload-artifact@v4
              with:
                name: test-report.html
                path: ./test-report.html
              
            

            
        