name: Template Images
on:
    workflow_call:
        inputs:
            image-tag:
                description: 'Tag for the Docker image'
                required: true
                type: string
            image-name:
                description: 'Name for the Docker image'
                required: true
                type: string
        secrets:
            DOCKER_HUB_USERNAME:
                required: true
            DOCKER_HUB_ACCESS_TOKEN:
                required: true

jobs:
    unit-test:
        uses: ./.github/workflows/template-teste.yaml

    builder:
        runs-on: ubuntu-latest
        needs: unit-test
        steps:
            - name: Checkout source code 
              uses: actions/checkout@v4

            - name: Creating Dockerfile
              run: |
                cat << 'EOF' > Dockerfile
                FROM python:3.12-slim
                
                WORKDIR /app
                
                COPY requirements.txt .
                RUN pip install --no-cache-dir -r requirements.txt
                
                COPY . .
                
                EXPOSE 8000
                
                EOF

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and export
              uses: docker/build-push-action@v5
              with:            
                context: .
                push: false
                tags: ${{ inputs.image-name }}:${{ inputs.image-tag }}
                outputs: type=docker,dest=/tmp/docker-image.tar

            - name: Uploading Docker Image
              uses: actions/upload-artifact@v4
              with:
                name: docker-image
                path: /tmp/docker-image.tar
                
            
    publisher:
        runs-on: ubuntu-latest
        needs: builder
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: docker-image
                path: /tmp
            - name: Loading Docker image
              run: |
                docker load -i /tmp/docker-image.tar
                docker image ls -a
            - name: Logging in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            - name: Pushing Docker image
              run: |
                docker push ${{ inputs.image-name }}:${{ inputs.image-tag }}
             