name: Template Tests

on:
    workflow_call:
        inputs:
            app:
                description: 'Application name'
                required: true
                type: string

jobs:
    unit-test:
        strategy:
            fail-fast: true
            max-parallel: 2
            matrix:
                os: [ubuntu-22.04, ubuntu-24.04, ubuntu-latest]
                python-version: ['3.10', '3.11', '3.12', '3.13']
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checking Source Code
              uses: actions/checkout@v4
            
            - name: Setting up Python
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}

            - name: Installing Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Running the tests
              run: |
                pytest --cov=${{ inputs.app }} --cov-report=html --html=${{ inputs.app }}-test-report.html --self-contained-html
            
            - name: Sending test results
              uses: actions/upload-artifact@v4
              with:
                name: ${{ inputs.app }}-test-report-${{ matrix.os }}-python${{ matrix.python-version }}
                path: ./${{ inputs.app }}-test-report.html
              
            

            
        